site_name: Documentação do Projeto de Comparação de Ações
theme:
  name: material
  features:
    - mermaid2
site_url: https://Kjonnathas.github.io/DataLake_MongoDB/
nav:
  - Home: home.md
  - Extração de Dados: extracao_dados.md
  - Visualização e Gráficos: visualizacao.md
plugins:
  - search
  - mermaid2
